[package]
name = "sql-lexer"
version.workspace = true
edition.workspace = true

[dependencies]
chumsky = { workspace = true }
ariadne = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
