[package]
name = "sql-engine"
version.workspace = true
edition.workspace = true

[dependencies]
sql-parser = { workspace = true }
sql-planner = { workspace = true }
sql-storage = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
csv = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
