[package]
name = "datalog-eval"
version = "0.1.0"
edition = "2021"

[dependencies]
datalog-planner = { path = "../datalog-planner" }
logical = { path = "../logical" }

[dev-dependencies]
internment = "0.8"
