[package]
name = "datalog-builtins"
version = "0.1.0"
edition = "2021"

[dependencies]
datalog-parser = { path = "../datalog-parser" }
sql-storage = { path = "../sql-storage" }

[dev-dependencies]
internment = "0.8"
