[package]
name = "datalog-builtins"
version = "0.1.0"
edition = "2021"

[dependencies]
datalog-parser = { path = "../datalog-parser" }
datalog-core = { path = "../datalog-core" }

[dev-dependencies]
internment = "0.8"
