[package]
name = "sql-tests"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
query = { path = "../query" }

[dev-dependencies]
proptest.workspace = true
tempfile = "3.10"
rand = "0.8"
