[package]
name = "logical"
version = "0.1.0"
edition = "2021"

[features]
test-utils = ["storage/test-utils"]

[dependencies]
storage = { path = "../storage" }
datalog-planner = { path = "../datalog-planner" }

[dev-dependencies]
internment = "0.8"
